object Constants {

  val DateFmtPattern = "yyyy-MM-dd"
  val DtTaxItemOfrList = "dt_tax_item_ofr_list"
  val KtTaxItemOfrList = "kt_tax_item_ofr_list"
  val AccountMaskRule = "account_mask_rule"
  val PaymentPurposeRule = "payment_purpose_rule"
  val DtTaxItem = "dt_tax_item"
  val KtTaxItem = "kt_tax_item"
  val DtAccountMaskList = "dt_account_mask_list"
  val KtAccountMaskList = "kt_account_mask_list"
  val Include = "INCLUDE"
  val PaymentPurpose = "payment_purpose"
  val PaymentPurposePatternList = "payment_purpose_pattern_list"
  val DtAccount = "dt_account"
  val KtAccount = "kt_account"
  val DtTaxItemOfr = "dt_tax_item_ofr"
  val KtTaxItemOfr = "kt_tax_item_ofr"
  val DtTaxItemAuto = "dt_tax_item_auto"
  val KtTaxItemAuto = "kt_tax_item_auto"
  val OperationDate = "operation_date"
  val CreatedTs = "created_ts"
  val InputDt = "input_dt"
  val IdpK = "id_pk"
  val TaxItemOfr = "tax_item_ofr"
  val TaxItemCode = "tax_item_code"
  val ActualFrom = "actual_from"
  val ActualTo = "actual_to"
  val EndDate = "end_date"

}
