object Constants {

  val DATE_FMT_PATTERN = "yyyy-MM-dd"
  val DT_TAX_ITEM_OFR_LIST = "dt_tax_item_ofr_list"
  val KT_TAX_ITEM_OFR_LIST = "kt_tax_item_ofr_list"
  val ACCOUNT_MASK_RULE = "account_mask_rule"
  val PAYMENT_PURPOSE_RULE = "payment_purpose_rule"
  val DT_TAX_ITEM = "dt_tax_item"
  val KT_TAX_ITEM = "kt_tax_item"
  val DT_ACCOUNT_MASK_LIST = "dt_account_mask_list"
  val KT_ACCOUNT_MASK_LIST = "kt_account_mask_list"
  val INCLUDE = "INCLUDE"
  val PAYMENT_PURPOSE = "payment_purpose"
  val PAYMENT_PURPOSE_PATTERN_LIST = "payment_purpose_pattern_list"
  val DT_ACCOUNT = "dt_account"
  val KT_ACCOUNT = "kt_account"
  val DT_TAX_ITEM_OFR = "dt_tax_item_ofr"
  val KT_TAX_ITEM_OFR = "kt_tax_item_ofr"
  val DT_TAX_ITEM_AUTO = "dt_tax_item_auto"
  val KT_TAX_ITEM_AUTO = "kt_tax_item_auto"
  val OPERATION_DATE = "operation_date"
  val CREATED_TS = "created_ts"
  val INPUT_DT = "input_dt"
  val ID_PK = "id_pk"
  val TAX_ITEM_OFR = "tax_item_ofr"
  val TAX_ITEM_CODE = "tax_item_code"
  val ACTUAL_FROM = "actual_from"
  val ACTUAL_TO = "actual_to"
  val END_DATE = "end_date"

}
